-- MySQL Script generated by MySQL Workbench
-- Sun May 23 23:07:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema futbol
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `futbol` ;

-- -----------------------------------------------------
-- Schema futbol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futbol` DEFAULT CHARACTER SET utf8 ;
USE `futbol` ;

-- -----------------------------------------------------
-- Table `futbol`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `futbol`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `Persona_id_Persona` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Persona1_idx` (`Persona_id_Persona` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Persona1`
    FOREIGN KEY (`Persona_id_Persona`)
    REFERENCES `futbol`.`Persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`Calificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`Calificaciones` ;

CREATE TABLE IF NOT EXISTS `futbol`.`Calificaciones` (
  `idCalificaciones` INT NOT NULL,
  `Critica` LONGTEXT NULL,
  `PromedioPartido` DOUBLE NULL,
  `PuntuacionJugador` DOUBLE NULL,
  `Jugador_idJugador` INT NOT NULL,
  PRIMARY KEY (`idCalificaciones`),
  INDEX `fk_Calificaciones_Jugador1_idx` (`Jugador_idJugador` ASC) VISIBLE,
  CONSTRAINT `fk_Calificaciones_Jugador1`
    FOREIGN KEY (`Jugador_idJugador`)
    REFERENCES `futbol`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`Infracciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`Infracciones` ;

CREATE TABLE IF NOT EXISTS `futbol`.`Infracciones` (
  `idInfracciones` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `Jugador_idJugador` INT NOT NULL,
  PRIMARY KEY (`idInfracciones`),
  INDEX `fk_Infracciones_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  INDEX `fk_Infracciones_Jugador1_idx` (`Jugador_idJugador` ASC) VISIBLE,
  CONSTRAINT `fk_Infracciones_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `futbol`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Infracciones_Jugador1`
    FOREIGN KEY (`Jugador_idJugador`)
    REFERENCES `futbol`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`Jugador` ;

CREATE TABLE IF NOT EXISTS `futbol`.`Jugador` (
  `idJugador` INT NOT NULL,
  `PromedioGeneral` DOUBLE NULL,
  `Asistencia` INT NULL,
  `CantidadInfracciones` INT NULL,
  `CantidadPartidosJugados` INT NULL,
  `FormaJuego` VARCHAR(100) NULL,
  `ModoSuscripcion` VARCHAR(100) NULL,
  `Penalizado` INT NULL,
  `Persona_id_Persona` INT NOT NULL,
  PRIMARY KEY (`idJugador`),
  INDEX `fk_Jugador_Persona_idx` (`Persona_id_Persona` ASC) VISIBLE,
  CONSTRAINT `fk_Jugador_Persona`
    FOREIGN KEY (`Persona_id_Persona`)
    REFERENCES `futbol`.`Persona` (`id_Persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`JugadoresxPartido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`JugadoresxPartido` ;

CREATE TABLE IF NOT EXISTS `futbol`.`JugadoresxPartido` (
  `idJugadoresxPartido` INT NOT NULL,
  `Jugador_idJugador` INT NOT NULL,
  `Partido_idPartido` INT NOT NULL,
  PRIMARY KEY (`idJugadoresxPartido`),
  INDEX `fk_JugadoresxPartido_Jugador1_idx` (`Jugador_idJugador` ASC) VISIBLE,
  INDEX `fk_JugadoresxPartido_Partido1_idx` (`Partido_idPartido` ASC) VISIBLE,
  CONSTRAINT `fk_JugadoresxPartido_Jugador1`
    FOREIGN KEY (`Jugador_idJugador`)
    REFERENCES `futbol`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JugadoresxPartido_Partido1`
    FOREIGN KEY (`Partido_idPartido`)
    REFERENCES `futbol`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`ListaJugadoresxPartido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`ListaJugadoresxPartido` ;

CREATE TABLE IF NOT EXISTS `futbol`.`ListaJugadoresxPartido` (
  `idListaJugadores` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  `Partido_idPartido` INT NOT NULL,
  `Jugador_idJugador` INT NOT NULL,
  PRIMARY KEY (`idListaJugadores`),
  INDEX `fk_ListaJugadores_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  INDEX `fk_ListaJugadoresxPartido_Partido1_idx` (`Partido_idPartido` ASC) VISIBLE,
  INDEX `fk_ListaJugadoresxPartido_Jugador1_idx` (`Jugador_idJugador` ASC) VISIBLE,
  CONSTRAINT `fk_ListaJugadores_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `futbol`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaJugadoresxPartido_Partido1`
    FOREIGN KEY (`Partido_idPartido`)
    REFERENCES `futbol`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaJugadoresxPartido_Jugador1`
    FOREIGN KEY (`Jugador_idJugador`)
    REFERENCES `futbol`.`Jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`Partido` ;

CREATE TABLE IF NOT EXISTS `futbol`.`Partido` (
  `idPartido` INT NOT NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `fk_Partido_Administrador1_idx` (`Administrador_idAdministrador` ASC) VISIBLE,
  CONSTRAINT `fk_Partido_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `futbol`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbol`.`Persona` ;

CREATE TABLE IF NOT EXISTS `futbol`.`Persona` (
  `id_Persona` INT NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(100) NULL,
  `Usuario` VARCHAR(100) NULL,
  `Contrasena` VARCHAR(100) NULL,
  `Nombre` VARCHAR(100) NULL,
  `Correo` VARCHAR(100) NULL,
  `Rol` VARCHAR(100) NULL,
  PRIMARY KEY (`id_Persona`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
