/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author eduar
 */
public class Infracciones extends javax.swing.JFrame {

    /**
     * Creates new form Infracciones
     */
    public Infracciones() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxJugador = new javax.swing.JComboBox<>();
        jComboBoxTipoInfraccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonEliminarInfraccion = new javax.swing.JButton();
        jButtonAplicarInfraccion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jugador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jComboBoxJugador.setBackground(new java.awt.Color(102, 102, 255));
        jComboBoxJugador.setAlignmentX(1.0F);
        jComboBoxJugador.setAlignmentY(1.0F);
        jComboBoxJugador.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jComboBoxJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 347, -1));

        jComboBoxTipoInfraccion.setBackground(new java.awt.Color(102, 102, 255));
        jComboBoxTipoInfraccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inasistencia al encuentro", "darse de baja sin remplazo", "otra razon" }));
        jComboBoxTipoInfraccion.setAlignmentX(1.0F);
        jComboBoxTipoInfraccion.setAlignmentY(1.0F);
        jComboBoxTipoInfraccion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jComboBoxTipoInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 347, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Infraccion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jButtonEliminarInfraccion.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEliminarInfraccion.setText("Eliminar infraccion");
        jButtonEliminarInfraccion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jButtonEliminarInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jButtonAplicarInfraccion.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAplicarInfraccion.setText("Aplicar infraccion");
        jButtonAplicarInfraccion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jButtonAplicarInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Infracciones2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Infracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Infracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Infracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Infracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Infracciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAplicarInfraccion;
    public javax.swing.JButton jButtonEliminarInfraccion;
    public javax.swing.JComboBox<String> jComboBoxJugador;
    public javax.swing.JComboBox<String> jComboBoxTipoInfraccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
